spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000
  datasource:
    url: jdbc:h2:mem:test_db;MODE=MYSQL
    username: sa
    password:
  test.database.replace: none
